// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsgebaziszyhgwezjiij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzZ2ViYXppc3p5aGd3ZXpqaWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDgzMzcsImV4cCI6MjA2Njg4NDMzN30.vKgk-FEmodi6l_4W0Rtjb0Dx8gUD6dn0JmRe-idiqR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});